displayName: TestAgent
schemaName: cr336_testAgent
accessControlPolicy: Any
authenticationMode: Integrated
authenticationTrigger: Always
configuration:
  channels:
    - channelId: MsTeams

    - channelId: Microsoft365Copilot

  settings:
    GenerativeActionsEnabled: true

  isAgentConnectable: true
  gPTSettings:
    defaultSchemaName: cr336_testAgent.gpt.default

  isLightweightBot: false
  aISettings:
    useModelKnowledge: false
    isFileAnalysisEnabled: true
    isSemanticSearchEnabled: true
    contentModeration: High
    optInUseLatestModels: false

  recognizer:
    kind: GenerativeAIRecognizer

authenticationConfiguration: {}
publishedOn: 2025-12-12T08:33:07.0000000Z
template: default-2.1.0
language: 1033